### ISSUE TITLE
PulseView AppImage

### ISSUE THREAD

**Issue by probonopd** [uwehermann/sigrok-util#1]
AppImage is a cross-distribution format for distributing portable software on Linux without needing superuser permissions to install the application. Since the Sigrok project does not provide an [AppImage](http://appimage.org/) yet, I took a different route and converted the existing binaries in the ppa to an AppImage. 

The AppImage contains PulseView and the firmware as well as the needed libraries (including Qt) which cannot be expected to be part of every target system. It is expected to run on most 64-bit desktop Linux systems.

Download it from here:
https://bintray.com/probono/AppImages/PulseView/_latestVersion#files

Just set the executable bit and run. No installation, no system libraries touched, no root needed. Should not interfere with any other versions you might or might not have on the system already.

This file specifies how to translate the ppa into an AppImage:
https://github.com/probonopd/AppImages/blob/master/recipes/meta/PulseView.yml

I think this would be a good way to provide nightly/continuous builds. It is almost no extra work if ppa builds are available for trusty or earlier.

It works nicely for me on an Ubuntu 16.04 system:

![PulseView](https://cloud.githubusercontent.com/assets/2480569/21352438/bc58188a-c6c1-11e6-86f3-99c65ed92d0c.png)

The above was made with a TSOP attached to a 6 EUR logic analyzer from China and [PulseView.AppImage](https://bintray.com/probono/AppImages/PulseView#files). It is expected that some fine-tuning and additional testing may be needed, and some fine-polish needs to be done by someone who knows the inner workings of the application.

It would be nice if the upstream project would start providing AppImages of nightlies.

**Comment by uwehermann** [comment]
Done, nightly AppImage builds are now available at sigrok.org/jenkins, thanks!
