### ISSUE TITLE
AppImages built on Jenkins require "too new" libstdc++ and glibc

### ISSUE THREAD

**Issue by probonopd** [uwehermann/sigrok-util#2]
AppImages built on Jenkins require "too new" libstdc++ and glibc for the AppImage to run on Ubuntu 14.04 (still-supported LTS release).

Would it be an option to build on trusty (chroot)?

Reference:
https://travis-ci.org/AppImage/AppImageHub/builds/266462005#L553-L584

**Comment by uwehermann** [comment]
Nightly AppImage builds are now available and are built on Ubuntu 14.04 Trusty i386/x86_64:

https://sigrok.org/jenkins/job/sigrok-native-appimage/platform=native-i686-appimage/
https://sigrok.org/jenkins/job/sigrok-native-appimage/platform=native-x86_64-appimage/

Please report further issues (if any) on IRC or at sigrok.org/bugzilla, we're not using github for "official" bug/PR handling (only read-only or per-person work-in-progress repos). Thanks!
